/* Programmable interval timer 8253/8254
 * oscillator frequency is approximately 1.193182 Mhz
 *
 * Channel 0 connected to PIC IRQ 0 (IRQ generated by low to high transition).
 * Channel 1 not used (legacy DMA refresh)
 * Channel 2 connected to PC speaker.
 */

#define PIT_CH0_DATA 0x40   // Channel 0 data port (read/write)
#define PIT_CH1_DATA 0x41   // Channel 1 data port (read/write)
#define PIT_CH2_DATA 0x42   // Channel 2 data port (read/write)
#define PIT_MODE_CMD 0x43   // mode/command register (write only)

#define PIT_CLK_SRC 1193182
